CI test suite
opengisch/signalo-oapif pull request #26
Opened 2023-04-03 09:27 UTC by why-not-try-calmer

The official test suite is not CI-ready; it uses a web client requiring manual input:

![Capture d’écran du 2023-04-03 10-58-50](https://user-images.githubusercontent.com/19554213/229469327-cd361758-b575-4971-aa4a-e5df0f235daa.png)

The wrapper script proposed here should make our lives a bit easier.

2023-04-03 10:03 UTC, why-not-try-calmer commented
This actually needs more debugging. WIP.

2023-04-04 08:11 UTC, olivierdalang requested changes

2023-04-04 08:11 UTC, olivierdalang commented on docker-compose.tests.yml
> +    build: ${PWD}/conformance-tests
paths are relative in docker compose already (you can just use ./conformance-tests)

2023-04-04 08:11 UTC, olivierdalang commented on docker-compose.tests.yml
> +      - ${PWD}/conformance-tests:/conformance-tests
same

2023-04-04 08:11 UTC, olivierdalang commented on conformance-tests/ogcf.py
> +        app_service = "django"
django:8000

2023-04-04 13:42 UTC, olivierdalang commented
Changed the approach to use directly the CLI. Unfortunately their provided Docker image doesn't contain the CLI executable. Fortunately someone did the work already: https://github.com/opengeospatial/ets-ogcapi-features10/issues/197

I also added the test at the end of the already existing quickstart test, as anyway the test always succeed for now because it exits with 0 even if there are issues. We can improve that once the test result start to be meaningful (e.g. once we're more or less conform).

The CI uploads the result to the artifacts (current run: https://github.com/opengisch/signalo-oapif/suites/12019989528/artifacts/631510246)

2023-04-04 13:43 UTC, olivierdalang approved these changes

2023-04-04 13:45 UTC, olivierdalang approved these changes

2023-04-04 14:39 UTC, merged